##私有仓库配置
##参考https://plugins.drone.io/plugins/docker

kind: pipeline
name: default

steps:
#自定义clone地址 参考： https://docs.drone.io/pipeline/docker/syntax/cloning/   --Custom Logic--
  - name: custom clone
    image: alpine/git
#挂载硬盘--容器绝对路径  参考：https://docs.drone.io/pipeline/docker/syntax/volumes/ --Host Volumes--
    volumes:
    - name: cache
      path: /mnt
    commands:
    - git clone https://github.com/evilhy/evilhy.ssr.github.com.git ./ssr
    - git checkout $DRONE_COMMIT
#    - rm -rf /mnt/*
#    - mkdir /mnt/evilhy.ssr.github.com
#    - mkdir /mnt/ts
#    - cp -rf /tmp/* /mnt/evilhy.ssr.github.com/
#    - cp -rf /drone/src/.git/* /mnt/ts/
  
  - name: build
    image: golang:latest
    environment:
      GOPROXY: https://mirrors.aliyun.com/goproxy/
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go abuild -o demo-app
      
  - name: wechat
    image: lizheming/drone-wechat
    settings:
      corpid: 
        from_secret: wechat_corpid
      corp_secret:
        from_secret: wechat_corp_secret
      agent_id: 
        from_secret: agent_id
      to_user: '@all'
#      to_party: 1
      to_tag: ${DRONE_REPO_NAME}
      msg_url: ${DRONE_BUILD_LINK}
      safe: 1
      btn_txt: more
      title: ${DRONE_REPO_NAME}
      message: >
        {%if success %}
          build {{build.number}} succeeded. Good job.
        {% else %}
          build {{build.number}} failed. Fix me please.
        {% endif %}
        
#  - name: greeting
#    image: alpine
#    commands:
#      - echo hello
#      - echo world
   

  - name: docker
    image: plugins/docker
    settings:
#insecure http协议true https协议false
      insecure: true
#registry 私有仓库地址  repo私有仓库写全地址 
      registry: my.icm.icu:1080
      repo: my.icm.icu:1080/library/devops-demo
      use_cache: true
#drone上secret上配置用户密码传参，也可以直接写账密username：xxx
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
#容器标签用变量，打包次数，其他变量参考官网https://docs.drone.io/pipeline/environment/reference/ and https://docs.drone.io/pipeline/environment/substitution/
      tags: ${DRONE_BUILD_NUMBER}
#      - ${DRONE_COMMIT_SHA:0:8}
#触发条件：master收到push时才触发打包推送
    when:
      event: push
      branch: master
      
      
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host: ssh.icm.icu
      username: root
      password: 060924...
      port: 22
      target: /tmp/ts
      source: .adds


        
#  - name: deploy
#    image: quay.io/ipedrazas/drone-helm
#    environment:
#      STABLE_REPO_URL: https://mirror.azure.cn/kubernetes/charts/
#      SERVICE_ACCOUNT: tiller
#      API_SERVER:
#        from_secret: api_server
#      KUBERNETES_TOKEN:
#        from_secret: kubernetes_token
#      KUBERNETES_CERTIFICATE:
#        from_secret: kubernetes_ca
#    settings:
#      client-only: true
#      wait: true
#      recreate_pods: true
#      chart: ./helm
#      release: drk8d
#      values_files: ["./helm/my-values.yaml"]
#      namespace: kube-ops
#    when:
#      event: push
#      branch: master
#
  # - name: release
  #   image: plugins/docker
  #   settings:
  #     repo: cnych/devops-demo
  #     # use_cache: true
  #     # cache_from: cnych/devops-demo
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
  #   tags:
  #     - ${DRONE_TAG##v}
  #     - ${DRONE_COMMIT_SHA:0:8}
  #     - latest
  #   when:
  #     event: tag
  #     branch: master

#挂载硬盘--物理绝对路径  参考：https://docs.drone.io/pipeline/docker/syntax/volumes/ --Host Volumes--
volumes:
- name: cache
  host:
    path: /mnt/dreon
